name = "DFA"
uuid = "68b8aea9-720c-4092-afc2-f92dd305eeec"
authors = ["afternone", "Alberto Barradas <abcsds@gmail.com>"]
version = "v1.0.0-DEV"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
